//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkTracker.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Commit_NoCommit_button_text {
            get {
                return ResourceManager.GetString("Commit_NoCommit_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to commit your work?.
        /// </summary>
        internal static string Commit_WantCommit_label_text {
            get {
                return ResourceManager.GetString("Commit_WantCommit_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Commit_YesCommit_button_text {
            get {
                return ResourceManager.GetString("Commit_YesCommit_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return back.
        /// </summary>
        internal static string Config_BackToPrevForm_button_text {
            get {
                return ResourceManager.GetString("Config_BackToPrevForm_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        internal static string Config_ChooseLanguge_Label_text {
            get {
                return ResourceManager.GetString("Config_ChooseLanguge_Label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select project for tracking.
        /// </summary>
        internal static string Config_ChooseProjDir_label_text {
            get {
                return ResourceManager.GetString("Config_ChooseProjDir_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Config_ChooseTGitDir_button_text {
            get {
                return ResourceManager.GetString("Config_ChooseTGitDir_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select directory with tortoise git.
        /// </summary>
        internal static string Config_ChooseTGitDir_label_text {
            get {
                return ResourceManager.GetString("Config_ChooseTGitDir_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select mode.
        /// </summary>
        internal static string Config_Mode1_label_text {
            get {
                return ResourceManager.GetString("Config_Mode1_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repo     local.
        /// </summary>
        internal static string Config_Mode2_label_text {
            get {
                return ResourceManager.GetString("Config_Mode2_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Config_ProjectSelection_Button_text {
            get {
                return ResourceManager.GetString("Config_ProjectSelection_Button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show commits.
        /// </summary>
        internal static string Main_ChooseClosestCommit_button_text {
            get {
                return ResourceManager.GetString("Main_ChooseClosestCommit_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open configuration.
        /// </summary>
        internal static string Main_ConfigFormOpening_button_text {
            get {
                return ResourceManager.GetString("Main_ConfigFormOpening_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording is paused.
        /// </summary>
        internal static string Main_CurrTrackState_label_pause_text {
            get {
                return ResourceManager.GetString("Main_CurrTrackState_label_pause_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording is on.
        /// </summary>
        internal static string Main_CurrTrackState_label_play_text {
            get {
                return ResourceManager.GetString("Main_CurrTrackState_label_play_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording is Stoped.
        /// </summary>
        internal static string Main_CurrTrackState_label_stop_text {
            get {
                return ResourceManager.GetString("Main_CurrTrackState_label_stop_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode: Local.
        /// </summary>
        internal static string Main_Mode_label_local_text {
            get {
                return ResourceManager.GetString("Main_Mode_label_local_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode: Repozitory.
        /// </summary>
        internal static string Main_Mode_label_repo_text {
            get {
                return ResourceManager.GetString("Main_Mode_label_repo_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project is selected.
        /// </summary>
        internal static string Main_ProjNotSelected_label_text {
            get {
                return ResourceManager.GetString("Main_ProjNotSelected_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        internal static string Main_RecordingFormOpening_Button_text {
            get {
                return ResourceManager.GetString("Main_RecordingFormOpening_Button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TGit directory not selected.
        /// </summary>
        internal static string Main_TortoiseFileNotSelected_label_text {
            get {
                return ResourceManager.GetString("Main_TortoiseFileNotSelected_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NotCommiting_No_button_text {
            get {
                return ResourceManager.GetString("NotCommiting_No_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string NotCommiting_Yes_button_text {
            get {
                return ResourceManager.GetString("NotCommiting_Yes_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you don&apos;t want to commit?.
        /// </summary>
        internal static string NotCommiting_YesNoDialog_label_text {
            get {
                return ResourceManager.GetString("NotCommiting_YesNoDialog_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NotStopedExit_No_button_text {
            get {
                return ResourceManager.GetString("NotStopedExit_No_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string NotStopedExit_Yes_button_text {
            get {
                return ResourceManager.GetString("NotStopedExit_Yes_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not stoped your recording?\nAre you sure, you want to exit?.
        /// </summary>
        internal static string NotStopedExit_YesNoDialog_label_text {
            get {
                return ResourceManager.GetString("NotStopedExit_YesNoDialog_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open configuration.
        /// </summary>
        internal static string Recording_ConfigFormOpening_button_text {
            get {
                return ResourceManager.GetString("Recording_ConfigFormOpening_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Main.
        /// </summary>
        internal static string Recording_ReturnToMain_button_text {
            get {
                return ResourceManager.GetString("Recording_ReturnToMain_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string WantCreateRepo_No_button_text {
            get {
                return ResourceManager.GetString("WantCreateRepo_No_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string WantCreateRepo_Yes_button_text {
            get {
                return ResourceManager.GetString("WantCreateRepo_Yes_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In current directory is no repository.\nWould you like to create one?.
        /// </summary>
        internal static string WantCreateRepo_YesNoDialog_label_text {
            get {
                return ResourceManager.GetString("WantCreateRepo_YesNoDialog_label_text", resourceCulture);
            }
        }
    }
}
