//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkTracker.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        internal static string Commit_form_text {
            get {
                return ResourceManager.GetString("Commit_form_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No commit was made. Are you sure you don&apos;t want to commit?.
        /// </summary>
        internal static string Commit_NoCommitMade_YesNoDialog_text {
            get {
                return ResourceManager.GetString("Commit_NoCommitMade_YesNoDialog_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you don&apos;t want to commit?.
        /// </summary>
        internal static string Commit_NotCommiting_YesNoDialog_label_text {
            get {
                return ResourceManager.GetString("Commit_NotCommiting_YesNoDialog_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to commit your work?.
        /// </summary>
        internal static string Commit_WantCommit_label_text {
            get {
                return ResourceManager.GetString("Commit_WantCommit_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return back.
        /// </summary>
        internal static string Config_BackToPrevForm_button_text {
            get {
                return ResourceManager.GetString("Config_BackToPrevForm_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        internal static string Config_ChooseLanguge_label_text {
            get {
                return ResourceManager.GetString("Config_ChooseLanguge_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select project for tracking.
        /// </summary>
        internal static string Config_ChooseProjDir_label_text {
            get {
                return ResourceManager.GetString("Config_ChooseProjDir_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select directory with tortoise git.
        /// </summary>
        internal static string Config_ChooseTGitDir_label_text {
            get {
                return ResourceManager.GetString("Config_ChooseTGitDir_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select mode.
        /// </summary>
        internal static string Config_Mode1_label_text {
            get {
                return ResourceManager.GetString("Config_Mode1_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local     repo.
        /// </summary>
        internal static string Config_Mode2_label_text {
            get {
                return ResourceManager.GetString("Config_Mode2_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application was unable access the record file of project, because it is used by other process.
        ///Try to close all processes, that make impossible to access this file.
        ///It will not be possible to make any record, unless is this problem fixed.
        ///After recovering of access to record file you can choose project again..
        /// </summary>
        internal static string Config_UnableToAccessCSV {
            get {
                return ResourceManager.GetString("Config_UnableToAccessCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configure_form_text {
            get {
                return ResourceManager.GetString("Configure_form_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no repository in given folder.
        ///Do you want to create new one in there?.
        /// </summary>
        internal static string Configure_WantToCreateRepoDialog {
            get {
                return ResourceManager.GetString("Configure_WantToCreateRepoDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recording.
        /// </summary>
        internal static string CurrTrackState_label_none_text {
            get {
                return ResourceManager.GetString("CurrTrackState_label_none_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording is paused.
        /// </summary>
        internal static string CurrTrackState_label_pause_text {
            get {
                return ResourceManager.GetString("CurrTrackState_label_pause_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording is on.
        /// </summary>
        internal static string CurrTrackState_label_start_text {
            get {
                return ResourceManager.GetString("CurrTrackState_label_start_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording is stoped.
        /// </summary>
        internal static string CurrTrackState_label_stop_text {
            get {
                return ResourceManager.GetString("CurrTrackState_label_stop_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last project commit.
        /// </summary>
        internal static string Main_Commit_label_text {
            get {
                return ResourceManager.GetString("Main_Commit_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///    Local mode active.
        /// </summary>
        internal static string Main_Commit_richTextBox_local_mode_text {
            get {
                return ResourceManager.GetString("Main_Commit_richTextBox_local_mode_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open configuration.
        /// </summary>
        internal static string Main_ConfigFormOpening_button_text {
            get {
                return ResourceManager.GetString("Main_ConfigFormOpening_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu.
        /// </summary>
        internal static string Main_form_text {
            get {
                return ResourceManager.GetString("Main_form_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///Invalid project selected.
        /// </summary>
        internal static string Main_InvalidProjectSelectedCommit_richTextBox {
            get {
                return ResourceManager.GetString("Main_InvalidProjectSelectedCommit_richTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///   No commit made yet.
        /// </summary>
        internal static string Main_NoCommitMade_richTextBox_text {
            get {
                return ResourceManager.GetString("Main_NoCommitMade_richTextBox_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See work progress.
        /// </summary>
        internal static string Main_ProgressFormOpening_button_text {
            get {
                return ResourceManager.GetString("Main_ProgressFormOpening_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid project is selected.
        /// </summary>
        internal static string Main_ProjNotSelected_label_text {
            get {
                return ResourceManager.GetString("Main_ProjNotSelected_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        internal static string Main_RecordingFormOpening_Button_text {
            get {
                return ResourceManager.GetString("Main_RecordingFormOpening_Button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid TGit directory is not selected.
        /// </summary>
        internal static string Main_TortoiseFileNotSelected_label_text {
            get {
                return ResourceManager.GetString("Main_TortoiseFileNotSelected_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode: Local.
        /// </summary>
        internal static string Mode_local_text {
            get {
                return ResourceManager.GetString("Mode_local_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode: Repozitory.
        /// </summary>
        internal static string Mode_repo_text {
            get {
                return ResourceManager.GetString("Mode_repo_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory of Project was changed.
        ///Please revert changes of project directory or choose another valid project in configuration..
        /// </summary>
        internal static string NonValidChangeOfProject_dir {
            get {
                return ResourceManager.GetString("NonValidChangeOfProject_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory of Tortoise Git was changed.
        ///Please choose new location in configuration..
        /// </summary>
        internal static string NonValidChangeOfTGit_dir {
            get {
                return ResourceManager.GetString("NonValidChangeOfTGit_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not stopped your recording?
        ///Are you sure, you want to exit?.
        /// </summary>
        internal static string NotStopedExit_YesNoDialog_label_text {
            get {
                return ResourceManager.GetString("NotStopedExit_YesNoDialog_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen project directory is not valid.
        /// </summary>
        internal static string NotValidProjectDirSelected {
            get {
                return ResourceManager.GetString("NotValidProjectDirSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid Tortoise Git directory selected.
        /// </summary>
        internal static string NotValidTGitDirChosen {
            get {
                return ResourceManager.GetString("NotValidTGitDirChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating.
        /// </summary>
        internal static string PhaseCreate_label_text {
            get {
                return ResourceManager.GetString("PhaseCreate_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debuging.
        /// </summary>
        internal static string PhaseDebug_label_text {
            get {
                return ResourceManager.GetString("PhaseDebug_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programing.
        /// </summary>
        internal static string PhaseProgr_label_text {
            get {
                return ResourceManager.GetString("PhaseProgr_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///         Local mode active.
        /// </summary>
        internal static string Progress_Commit_richTextBox_local_mode_text {
            get {
                return ResourceManager.GetString("Progress_Commit_richTextBox_local_mode_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work duration:.
        /// </summary>
        internal static string Progress_CompDuration_label_text {
            get {
                return ResourceManager.GetString("Progress_CompDuration_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work duration (including paused intervals):.
        /// </summary>
        internal static string Progress_CompDurationWithStop_label_text {
            get {
                return ResourceManager.GetString("Progress_CompDurationWithStop_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string Progress_Day_label_text {
            get {
                return ResourceManager.GetString("Progress_Day_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of work made during individual hours of day.
        /// </summary>
        internal static string Progress_DayMean_label_text {
            get {
                return ResourceManager.GetString("Progress_DayMean_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 days.
        /// </summary>
        internal static string Progress_Days7_label_text {
            get {
                return ResourceManager.GetString("Progress_Days7_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work progression.
        /// </summary>
        internal static string Progress_form_text {
            get {
                return ResourceManager.GetString("Progress_form_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From day.
        /// </summary>
        internal static string Progress_From_label_text {
            get {
                return ResourceManager.GetString("Progress_From_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///     Invalid project selected.
        /// </summary>
        internal static string Progress_InvalidProjectSelectedCommit_richTextBox {
            get {
                return ResourceManager.GetString("Progress_InvalidProjectSelectedCommit_richTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        internal static string Progress_Month_label_text {
            get {
                return ResourceManager.GetString("Progress_Month_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To day.
        /// </summary>
        internal static string Progress_To_label_text {
            get {
                return ResourceManager.GetString("Progress_To_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open configuration.
        /// </summary>
        internal static string Recording_ConfigFormOpening_button_text {
            get {
                return ResourceManager.GetString("Recording_ConfigFormOpening_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work phase.
        /// </summary>
        internal static string Recording_Faze_label_text {
            get {
                return ResourceManager.GetString("Recording_Faze_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        internal static string Recording_form_text {
            get {
                return ResourceManager.GetString("Recording_form_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application was unable access the record file of project, because it is used by other process.
        ///Try to close all processes, that make impossible to access this file.
        ///State of recording will be set to the previous one and after recovering of access you can change it again..
        /// </summary>
        internal static string Recording_UnableToAccessCSV {
            get {
                return ResourceManager.GetString("Recording_UnableToAccessCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Main.
        /// </summary>
        internal static string ReturnToMain_button_text {
            get {
                return ResourceManager.GetString("ReturnToMain_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure has occured during calling of Tortoise Git process. 
        ///Try to call it again or manage Tortoise Git directory in configuration..
        /// </summary>
        internal static string RunTortoiseGitFailure {
            get {
                return ResourceManager.GetString("RunTortoiseGitFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while choosing project directory
        ///Try again.
        /// </summary>
        internal static string SomethingWentWrongProjectDialog {
            get {
                return ResourceManager.GetString("SomethingWentWrongProjectDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while choosing Tortoise Git directory
        ///Try again.
        /// </summary>
        internal static string SomethingWentWrongTGitDialog {
            get {
                return ResourceManager.GetString("SomethingWentWrongTGitDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In current directory is no repository.\nWould you like to create one?.
        /// </summary>
        internal static string WantCreateRepo_YesNoDialog_label_text {
            get {
                return ResourceManager.GetString("WantCreateRepo_YesNoDialog_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
